apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:1.4.1
        ports:
        - containerPort: 80